### ISSUE TITLE
#include <input_large.h>

### ISSUE THREAD

**Issue by nikkadim** [ironhide23586/CUDA-Connected-Component-Labelling#1]
What is input_large.h in includes?
Thanks.

**Comment by Shaluols** [comment]
Hi, could you tell us where is the  input_large.h?
Thanks!

**Comment by ironhide23586** [comment]
Input large file basically generates a large 2D matrix of floats which represents the input image. It initializes memory and returns the the pointer as a result of get_input() function called at 3rd line after the main() declaration. 

--
Yours Sincerely,
Souham Biswas
Computer Science Graduate Student (MS)
Illinois Institute of Technology, Chicago, IL, USA 


Contact No.: +1-(312)-866-1163 (Mob.)

**Comment by Shaluols** [comment]
OK, thank you !
